service: holy-back
frameworkVersion: "3"

provider:
  name: aws
  runtime: nodejs20.x
  stage: production
  region: sa-east-1
  iam:
    role:
      statements:
        - Effect: "Allow"
          Action:
            - "s3:ListBucket"
          Resource:
            - "arn:aws:s3:::holy-back-production-serverlessdeploymentbucket-cw1vdhfs1zil"
        - Effect: "Allow"
          Action:
            - "s3:GetObject"
            - "s3:PutObject"
            - "s3:DeleteObject"
          Resource:
            - "arn:aws:s3:::holy-back-production-serverlessdeploymentbucket-cw1vdhfs1zil/*"

functions:
  app:
    handler: src/index.handler
    timeout: 10
    events:
      - http:
          path: /
          method: ANY
          cors:
            origin: '*'
            headers:
            - Content-Type
            - Token
            - token
            - X-Amz-Date
            - Authorization
            - Access-Control-Allow-Origin
            - X-Api-Key
            - X-Amz-Security-Token
            - X-Amz-User-Agent
            allowCredentials: false
      - http:
          path: /{proxy+}
          method: ANY
          cors:
            origin: '*'
            headers:
            - Content-Type
            - Token
            - token
            - X-Amz-Date
            - Authorization
            - Access-Control-Allow-Origin
            - X-Api-Key
            - X-Amz-Security-Token
            - X-Amz-User-Agent
            allowCredentials: false

# Define service-wide environment variables here if needed
# environment:
#   variable1: value1

# Add packaging information here if needed
# package:
#   patterns:
#     - '!exclude-me.js'
#     - '!exclude-me-dir/**'
#     - include-me.js
#     - include-me-dir/**

# Add CloudFormation resource templates here if needed
# resources:
#   Resources:
#     NewResource:
#       Type: AWS::S3::Bucket
#       Properties:
#         BucketName: my-new-bucket
#   Outputs:
#     NewOutput:
#       Description: "Description for the output"
#       Value: "Some output value"
